name: Deploy CDK Project
on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - closed
    branches:
      - main
      - staging

jobs:
  deploy_aws_cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::842537737558:role/trip-logger-github-ci-role
          aws-region: ${{ vars.REGION }}

      - name: cdk diff
        run: npx aws-cdk diff

      - name: cdk deploy App Stack
        run: npx aws-cdk deploy --exclusively AppStack

      # - name: Trigger Amplify Build
      #   run: |
      #     if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/develop" ]; then
      #       WEBHOOK_URL="${{ secrets.DEVELOP_WEBHOOK_URL }}"
      #     elif [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
      #       WEBHOOK_URL="${{ secrets.MAIN_WEBHOOK_URL }}"
      #     fi

      #     if [ ! -z "${WEBHOOK_URL}" ]; then
      #       curl -X POST -d {} "${WEBHOOK_URL}" -H "Content-Type:application/json"
      #     fi
